function Clabel = colormaps
Clabel = {'ColormapRed','ColormapBlue','ColormapGreen',...
            'gray','parula','kjet','kjetw','jet','hsv','hot','cool','spring',...
            'summer','autumn','winter','bone','copper','pink','lines',...
            'flag'};
Clabel = Clabel';