function [G,sigma_array] = TS_GaussianKernel(Reso,ObjSize)

GaussFil_sigma_coef = 1;
sigma_array = [ObjSize(2)/Reso(2)/(2*sqrt(2*log(2)))*GaussFil_sigma_coef ...
    ObjSize(1)/Reso(1)/(2*sqrt(2*log(2)))*GaussFil_sigma_coef ...
    ObjSize(3)/Reso(3)/(2*sqrt(2*log(2)))*GaussFil_sigma_coef];
fprintf([mfilename '\n Input Reso.:' num2str(Reso,' %.3f'),...
    '\n Input Obj.Size: ' num2str(ObjSize,' %.1f') ,...
    '\n Calculated Sigma :' num2str(sigma_array,' %.5f'),...
    '\n\n'])
KernelSize = 2*ceil(2*sigma_array)+1; %% default of imgaussianfilt3 
G = Gaussian3D(sigma_array,KernelSize);